//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломная_работа___Гимаев_Амир
{
    using System;
    using System.Collections.Generic;
    
    public partial class Digitized
    {
        public int IdCase { get; set; }
        public System.DateTime DateOfDigitization { get; set; }
        public byte[] DigitizedFile { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Documents Documents1 { get; set; }
    }
}
