//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломная_работа___Гимаев_Амир
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int IdCase { get; set; }
        public string Name { get; set; }
        public int IdFoundation { get; set; }
        public int NumberCase { get; set; }
        public int PageCount { get; set; }
        public Nullable<System.DateTime> FromTheBeginningOf { get; set; }
        public Nullable<System.DateTime> To { get; set; }
    
        public virtual Digitized Digitized { get; set; }
        public virtual Foundations Foundations { get; set; }
        public virtual Digitized Digitized1 { get; set; }
    }
}
