//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломная_работа___Гимаев_Амир
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foundations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Foundations()
        {
            this.Documents = new HashSet<Documents>();
        }
    
        public int IdFoundation { get; set; }
        public string Name { get; set; }
        public byte IdTypeOfFoundation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual TypeOfFoundation TypeOfFoundation { get; set; }
    }
}
